### PR TITLE
Update the filtering of time for cloud copy

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR update the retrieval of data from cloud copy!

### CODE REVIEW

**Comment by lsetiawan** [comment]
@pshivraj Any thoughts on this credential failures?

**Comment by pshivraj** [comment]
> @pshivraj Any thoughts on this credential failures?

I see one failure owing to missing funtion `filter_ncurls()` which apparently looks like has been removed from current pull request. Is there any reason why this module is not needed anymore ?

**Comment by pshivraj** [comment]
> > @pshivraj Any thoughts on this credential failures?
> 
> I see one failure owing to missing function `filter_ncurls() and get_start_end_dates()` which apparently looks like has been removed from current pull request. Is there any reason why this module is not needed anymore ?

I tested this locally, since this pull request uses different method to get `ncurls` so taking away one test case should make this build pass.

**Comment by lsetiawan** [comment]
> I see one failure owing to missing function filter_ncurls() and get_start_end_dates() which apparently looks like has been removed from current pull request. Is there any reason why this module is not needed anymore ?

Yea because we don't need it anymore because the new processed netcdf.

**Comment by lsetiawan** [comment]
@pshivraj Does this work locally now? If so please merge. Thanks :)

**Comment by pshivraj** [comment]
Works fine with test case fix. Merging it

**Pull request merged**
