### PR TITLE
Blacken

### PR DESCRIPTION
**Pull request by ocefpaf**
@lsetiawan the second last commit is the massive black changes that hopefully will happen only once.

From now one all people should do is to run the `make style` before committing code.

### CODE REVIEW

**Comment by lsetiawan** [comment]
COOL! You gotta show me how this works sometime :smile:

**Comment by ocefpaf** [comment]
> COOL! You gotta show me how this works sometime

Next week ;-p

PS: if you create the dev env like in the `.travis.yml` file you should be able to execute all the commands in the `Makefile`.

**Comment by lsetiawan** [comment]
So there's no more coding standard checks with this change?

**Comment by ocefpaf** [comment]
> So there's no more coding standard checks with this change?

Nope. Just ensure people will run "make style" before submitting a PR.
You can setup a git hook but I'll leave that for later. (Need to get back to the tutorials ;-p

**Comment by lsetiawan** [comment]
Failing due to 401. All good here. Thanks!

**Pull request merged**
