### PR TITLE
Don't package the tests folder.

### LINKED ISSUE #110: find_packages() is packaging `tests` as a module
I'm not sure you need a `__init__.py` in the test directory. The side effect is that it ends up packaged and clobber a simple/common namespace "tests"

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #110

### CODE REVIEW

**Comment by lsetiawan** [comment]
This is an awesome PR! Thank you!

**Comment by lsetiawan** [comment]
This is failing due to 401 Auth Error since PR is coming from outside user.

**Comment by ocefpaf** [comment]
@lsetiawan the error seems to be unrelated to this PR. Can you take a look? Should we make the `UNAUTHORIZED` ones as `xfail`?

PS: are you opened to remove the `coding_standards` test and adopt black instead?

**Comment by lsetiawan** [comment]
The UNAUTHORIZED is because the credentials to OOI is setup for this organization only. I'm not familiar with black, but if that's better then I am open to it :) With your help of course hehe

**Comment by ocefpaf** [comment]
> The UNAUTHORIZED is because the credentials to OOI is setup for this organization only.

Then marking then as `xfail` makes sense to make it easier to review PRs from people outside of the organization.

> I'm not familiar with black, but if that's better then I am open to it :) With your help of course hehe

https://black.readthedocs.io/en/stable/

It is a single massive commit, after that one should either set a pre-commit hook it a run a Makefile. The advantage is to never worry about code style again.

**Pull request merged**
